# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site informations
title: 哒黍·馒头
email: tjianadm@live.com
author: tjian
description: > # this means to ignore newlines until "baseurl:"
  哒黍·馒头的个人小站，包括但可能不限于以下内容：技术积累、生活感想、书籍推荐和创意点子。
additional: >
  哒黍·馒头的个人小站，除了 Jekyll 原生部分，站点样式、布局规则都是手敲，欢迎邮件讨论自建博客技术细节。
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#

permalink: /:year/:month/:day/:title

# socail account
github_username: tjian123
zhihu_username: tjian123

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  coderaw_line_numbers: :inline
highlighter: rouge
sass:
  style: compressed
excerpt_separator: <!-- more --> #用于显示文章摘要

# Default style: default, dark, light
bodyClass: default

include: [_pages]
exclude: [TODO, README.md]

# 分页
paginate            : 5          # 定义每页数量
paginate_path       : "/blog/page:num"  # 定义分页结果

# 是否开启背景图片
enable_bg_img: false